name: publish
on:
  pull_request:
    branches:
      - 'master'
    types: [closed]
    paths:
      - 'index.js'
      - 'modules/**'
      - 'package.json'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: Install dependencies
      run: npm i
    - name: Test
      run: npm test
    - name: Publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
